# Generated by Django 4.1.3 on 2022-11-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='profile',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_logo/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='var_or_tax',
            field=models.FloatField(default=0),
        ),
    ]
