# Generated by Django 4.1.3 on 2022-12-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_latitude_restaurant_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
