# Generated by Django 4.1.3 on 2022-12-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_restaurant_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
