# Generated by Django 4.1.3 on 2022-12-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
