# Generated by Django 4.1.3 on 2022-12-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_remove_food_price_alter_food_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='extras_cover_image/')),
                ('createdAt', models.DateField(auto_now=True)),
                ('updatedAt', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='extra',
            field=models.ManyToManyField(blank=True, to='food.extra'),
        ),
    ]
