# Generated by Django 4.1.3 on 2022-12-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_extra_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
